<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>id.co.javara</groupId>
        <artifactId>javara</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>javara-bom</artifactId>
    <packaging>pom</packaging>

    <name>JAVARA Bill of Materials</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>id.co.javara</groupId>
                <artifactId>javara-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>id.co.javara</groupId>
                <artifactId>javara-ofs</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>id.co.javara</groupId>
                <artifactId>javara-tafj</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>id.co.javara</groupId>
                <artifactId>javara-iris</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>id.co.javara</groupId>
                <artifactId>javara-jms</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>id.co.javara</groupId>
                <artifactId>javara-app</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>id.co.javara</groupId>
                <artifactId>javara-client</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>id.co.javara</groupId>
                <artifactId>javara-starter</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- Spring Boot BOM -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
